development:
  adapter: postgresql
  host: localhost
  username: user
  password: password
  database: safecycling-dev

test:
  adapter: postgresql
  host: localhost
  username: user
  password: password
  database: safecylcing-test
